-- Starfall Vengeance — final integrated runtime
local Assets=require("assets"); local Modes=require("modes"); local Player=require("player"); local Bullet=require("bullet"); local Enemy=require("enemy"); local PowerUp=require("powerup"); local Weapons=require("weapons"); local XP=require("xp"); local Particles=require("particles"); local Effects=require("effects"); local Camera=require("camera"); local Sound=require("sound"); local Drone=require("drone"); local Profile=require("profile"); local Ads=require("ads"); local TouchControls=require("touchcontrols"); local util=require("util")
local state="menu"; local run,player; local bullets,enemies,powerups,drones={},{},{},{}; local weapons,currentWeapon,xpData; local particles,effects,camera,sound,touch; local fonts={}; local selectedMode=1; local modeIds={"campaign","endless","gauntlet"}; local time=0; local mouseDown=false; local mobile=false; local quality="high"; local waveText=0; local flashT=0; local flash={1,1,1}; local best=0; local newBest=false; local reason=""
local function F(n) fonts[n]=fonts[n] or love.graphics.newFont(n); return fonts[n] end
local function clamp(v,a,b) return math.max(a,math.min(b,v)) end
local function inr(x,y,r) return x>=r.x and x<=r.x+r.w and y>=r.y and y<=r.y+r.h end
local function safe(o,m,...) if o and type(o[m])=="function" then local ok,r=pcall(o[m],o,...); if ok then return r end end end
local function sfx(n,v) safe(sound,"playSound",n,v) end
local function hitfx(r,g,b,a) flashT=math.max(flashT,a or .15); flash={r,g,b}; safe(effects,"flash",r,g,b,a or .15) end
local function panel(x,y,w,h,a) love.graphics.setColor(.008,.018,.045,a or .86); love.graphics.rectangle("fill",x,y,w,h,14,14); love.graphics.setColor(.18,.65,1,.3); love.graphics.rectangle("line",x,y,w,h,14,14) end
local function button(r,c) local mx,my=love.mouse.getPosition(); local h=inr(mx,my,r); c=c or {.18,.65,1}; love.graphics.setColor(0,0,0,.4); love.graphics.rectangle("fill",r.x+4,r.y+5,r.w,r.h,10,10); love.graphics.setColor(c[1],c[2],c[3],h and .98 or .72); love.graphics.rectangle("fill",r.x,r.y,r.w,r.h,10,10); local fs=#(r.text or "")>15 and 16 or 20; love.graphics.setFont(F(fs)); love.graphics.setColor(1,1,1,.92); love.graphics.printf(r.text or "",r.x,r.y+(r.h-F(fs):getHeight())/2,r.w,"center") end
local function reset()
    bullets,enemies,powerups,drones={},{},{},{}; weapons=Weapons.new(); currentWeapon="pistol"; xpData=XP.new(); player=Player.new(love.graphics.getWidth()/2,love.graphics.getHeight()/2)
    player.fireRateMultiplier=1; player.damageMultiplier=1; player.magneticRange=0; player.piercingBullets=false; player.extraProjectiles=0; player.hasSideDrones=false; player.hasOrbitDrones=false; player.hasHomingMissile=false; player.explosionSizeMultiplier=1; player.droneDamageMultiplier=1
    run=Modes.newRun(modeIds[selectedMode]); waveText=1.5; mouseDown=false; if mobile then touch=TouchControls.new(); touch:setQuality(quality) end
end
local function addDrones()
    local side,orb=0,0; for _,d in ipairs(drones) do if d.formation=="side" then side=side+1 elseif d.formation=="orbit_upgrade" then orb=orb+1 end end
    if player.hasSideDrones and side<2 then for i=side+1,2 do local d=Drone.new(player.x,player.y,"attack","player"); d.formation="side"; d.formationIndex=i; d.formationCount=2; d:setQuality(quality); drones[#drones+1]=d end end
    if player.hasOrbitDrones and orb<2 then for i=orb+1,2 do local d=Drone.new(player.x,player.y,"attack","player"); d.formation="orbit_upgrade"; d.formationIndex=i; d.formationCount=2; d.orbitSpeed=2.5; d:setQuality(quality); drones[#drones+1]=d end end
end
local function spawnEnemy(kind,elite)
    local x,y=util.getRandomEdgePosition(); local pool={"swarmer"}; if run.wave>=2 then pool[#pool+1]="turret" end; if run.wave>=3 then pool[#pool+1]="sniper" end; if run.wave>=4 then pool[#pool+1]="bomber" end; kind=kind or pool[math.random(#pool)]
    local e=Enemy.new(x,y,kind,Assets.get(kind)); local r=Modes.waveRules(run); e.health=e.health*r.health; e.maxHealth=e.health; e.speed=e.speed*r.speed; if r.fireMultiplier and e.shootCooldown>0 then e.shootCooldown=e.shootCooldown*r.fireMultiplier end
    if elite then e.health=e.health*1.8; e.maxHealth=e.health; e.speed=e.speed*1.15; e.score=e.score*3; e.elite=true end; e._scored=false; enemies[#enemies+1]=e
end
local function boss() spawnEnemy("miniboss",false); sfx("explosion",.7); hitfx(.7,.2,1,.2); safe(camera,"shake",14,.4,2) end
local function giveReward() local w,h=love.graphics.getWidth(),love.graphics.getHeight(); local p=PowerUp.new(math.random(80,w-80),math.random(90,h-90)); p:setQuality(quality); powerups[#powerups+1]=p end
local function levelUp() state="upgrade"; _G.__SV_CHOICES=XP.getRandomUpgrades(3); sfx("levelup",.7); hitfx(.2,.8,1,.2) end
local function scoreKill(e)
    run.kills=run.kills+1; run.combo=run.combo+1; run.comboTimer=0; run.bestCombo=math.max(run.bestCombo,run.combo); run.threat=clamp(run.threat+.025,0,1)
    local m=Modes.get(run.id); local gain=(e.score or 10)*(1+math.min(run.combo,25)*.06)*m.scoreMultiplier*(m.rewardMultiplier or 1)*(e.elite and 1.75 or 1); run.score=math.floor(run.score+gain)
    local xpg=(Enemy.types[e.type] and Enemy.types[e.type].xp or 10)*m.xpMultiplier; if player.powerups.xpboost>0 then xpg=xpg*2 end; if XP.addXP(xpData,xpg) then levelUp() end
    safe(effects,"addDamageNumber",e.x,e.y,"+"..math.floor(gain),e.elite); safe(particles,"explosion",e.x,e.y,e.elite and 1.8 or .9,e.elite and "electric" or "default"); safe(camera,"shake",e.elite and 8 or 3,.1,1); sfx(e.elite and "heavyShoot" or "hit",.3); if e.elite or math.random()<.09 then giveReward() end
end
local function finish(win,msg)
    if state=="gameover" then return end; run.completed=win; reason=msg; newBest=run.score>best; best=math.max(best,run.score); state="gameover"; mouseDown=false
    if Profile.hasProfile() then Profile.updateStats(run.score,math.floor(run.score/50)); Profile.incrementGamesPlayed() end; Ads.onGameOver(run.score); sfx(win and "levelup" or "death",.8); safe(particles,"explosion",player.x,player.y,2.3,"fire")
end
local function playerDamage(amount)
    if player:takeDamage(amount) then
        run.combo=0; hitfx(1,.1,.1,.2); sfx("hit",.5); safe(camera,"shake",8,.16,2)
        if player.health<=0 then
            if run.lives>1 then
                run.lives=run.lives-1; player.health=player.maxHealth; player.powerups.invincible=2.0; bullets={}; hitfx(.2,.75,1,.24); sfx("highDown",.5); safe(effects,"notification","LIFE LOST — "..run.lives.." REMAINING",{.6,.85,1})
            else finish(false,"SHIP DESTROYED") end
        end
        return true
    end
    return false
end
local function startRun()
    reset(); state="playing"; Ads.onGameStart(); sfx("menu",.25); safe(sound,"playMusic"); local r=Modes.waveRules(run); run.target=r.target; run.spawned=0; run.spawnTimer=0; if r.boss then boss() end
end
local function advance()
    run.score=run.score+math.floor(run.wave*12*Modes.get(run.id).scoreMultiplier); sfx("highUp",.65); hitfx(.1,.8,1,.12)
    if run.id=="campaign" and run.wave>=30 then finish(true,"CAMPAIGN COMPLETE"); return end
    if run.id=="gauntlet" then if run.trial>=8 then finish(true,"GAUNTLET CLEARED"); return end; Modes.nextGauntletTrial(run) else run.wave=run.wave+1 end
    local r=Modes.waveRules(run); run.target=r.target; run.spawned=0; run.spawnTimer=0; run.trialTimer=run.trialTimer or 0; waveText=1.1; if r.boss then boss() end
end
local function shoot(a)
    local d=Weapons.types[currentWeapon]; if not d or player.shootCooldown>0 or not Weapons.hasAmmo(weapons,currentWeapon) then return end
    local n=(d.bulletCount or 1)+(player.extraProjectiles or 0); for i=1,n do local aa=a; if n>1 then aa=aa+(i-(n+1)/2)*(d.spread or 0)/n end; local b=Bullet.new(player.x,player.y,aa,"player",player.bulletColor or "yellow"); b.damage=(d.damage or 1)*10*(player.damageMultiplier or 1); b.speed=d.bulletSpeed or 400; b.vx=math.cos(aa)*b.speed; b.vy=math.sin(aa)*b.speed; b.piercing=player.piercingBullets or d.piercing; b.homing=player.powerups.homing>0; b.homingStrength=3.2; b.explosion=player.powerups.explosive>0; b.explosionRadius=42*(player.explosionSizeMultiplier or 1); bullets[#bullets+1]=b end
    Weapons.useAmmo(weapons,currentWeapon,1); player.shootCooldown=(d.fireRate or .2)*(player.fireRateMultiplier or 1); sfx((d.fireRate or .2)<.15 and "shoot" or "heavyShoot",.3); safe(particles,"thruster",player.x-math.cos(a)*12,player.y-math.sin(a)*12,a+math.pi,.8)
end
local function combat(dt)
    run.elapsed=run.elapsed+dt; if run.combo>0 then run.comboTimer=run.comboTimer+dt; if run.comboTimer>2.8 then run.combo=0 end end
    local mx,my=0,0; local ax,ay=0,0; local firing=love.mouse.isDown(1); if mobile and touch then mx,my=touch:getMovement(); ax,ay=touch:getAimDirection(); firing=firing or touch:isShooting() end
    player:update(dt,mx,my,mobile and "mobile" or "pc"); local a=util.angle(player.x,player.y,love.mouse.getX(),love.mouse.getY()); if mobile and math.abs(ax)+math.abs(ay)>.1 then a=math.atan2(ay,ax); player.hasAimOverride=true; player.aimAngle=a else player.hasAimOverride=false end; if firing then shoot(a) end
    for _,b in ipairs(bullets) do b:update(dt,enemies) end
    for _,e in ipairs(enemies) do
        e:update(dt,player.x,player.y)
        if e:canShoot() then local aa=util.angle(e.x,e.y,player.x,player.y); local eb=Bullet.new(e.x,e.y,aa,"enemy",e.type=="sniper" and "blue" or "red"); eb.damage=e.damage*(Modes.waveRules(run).damageMultiplier or 1); eb.speed=e.type=="sniper" and 330 or 260; eb.vx=math.cos(aa)*eb.speed; eb.vy=math.sin(aa)*eb.speed; bullets[#bullets+1]=eb; sfx("retroShoot",.16) end
        if e.type=="miniboss" then e._t=(e._t or 1.8)-dt; if e._t<=0 then e._t=2.2; for i=1,10 do local aa=i*math.pi*.2; local eb=Bullet.new(e.x,e.y,aa,"enemy","purple"); eb.damage=e.damage*1.25; eb.speed=220; eb.vx=math.cos(aa)*eb.speed; eb.vy=math.sin(aa)*eb.speed; bullets[#bullets+1]=eb end; sfx("heavyShoot",.2) end end
    end
    for _,p in ipairs(powerups) do p:update(dt) end
    for _,d in ipairs(drones) do local a2=safe(d,"update",dt,player,enemies,bullets,powerups,{}); if a2 and a2.type=="shoot" then local b=Bullet.new(d.x,d.y,a2.angle or 0,"player",a2.color or "yellow"); b.damage=(a2.damage or 4)*(player.droneDamageMultiplier or 1); b.speed=420; b.vx=math.cos(a2.angle or 0)*b.speed; b.vy=math.sin(a2.angle or 0)*b.speed; bullets[#bullets+1]=b end end
    for _,b in ipairs(bullets) do
        if not b.dead and b.owner=="player" then
            for _,e in ipairs(enemies) do
                if not e.dead and util.checkCollision(b.x,b.y,b.radius,e.x,e.y,e.radius) then
                    e:takeDamage(b.damage); safe(particles,"impact",e.x,e.y,util.angle(b.x,b.y,e.x,e.y),1)
                    if b.explosion then local rr=b.explosionRadius or 40; b.dead=true; safe(particles,"explosion",b.x,b.y,rr/40,"fire"); sfx("explosion",.22); for _,e2 in ipairs(enemies) do if e2~=e and not e2.dead and util.distance(b.x,b.y,e2.x,e2.y)<rr then e2:takeDamage(b.damage*.6); if e2.dead and not e2._scored then e2._scored=true; scoreKill(e2) end end end else b.dead=not b.piercing end
                    if e.dead and not e._scored then e._scored=true; scoreKill(e) end; if not b.piercing then break end
                end
            end
        elseif not b.dead and b.owner=="enemy" and util.checkCollision(b.x,b.y,b.radius,player.x,player.y,player.radius) then b.dead=true; playerDamage(b.damage) end
    end
    for _,e in ipairs(enemies) do if not e.dead and util.checkCollision(e.x,e.y,e.radius,player.x,player.y,player.radius) and e:canDamagePlayer() then playerDamage(e.damage*1.25) end end
    util.removeDeadEntities(bullets); util.removeDeadEntities(enemies)
    for i=#powerups,1,-1 do local p=powerups[i]; if player.magneticRange>0 and util.distance(player.x,player.y,p.x,p.y)<player.magneticRange then local aa=util.angle(p.x,p.y,player.x,player.y); p.x=p.x+math.cos(aa)*220*dt; p.y=p.y+math.sin(aa)*220*dt end; if util.checkCollision(player.x,player.y,player.radius,p.x,p.y,p.radius) then player:applyPowerUp(p.type); table.remove(powerups,i); sfx("shield",.55); safe(particles,"healEffect",player.x,player.y,20) end end
    addDrones(); local r=Modes.waveRules(run); if run.spawned<run.target then run.spawnTimer=run.spawnTimer+dt; if run.spawnTimer>=r.spawnDelay then run.spawnTimer=0; run.spawned=run.spawned+1; spawnEnemy(nil,run.spawned>3 and math.random()<r.eliteChance) end elseif #enemies==0 and state=="playing" then advance() end
    if run.id=="gauntlet" then run.trialTimer=run.trialTimer+dt; if run.trialTimer>=run.trialDuration then enemies={}; advance() end end
end
local function space()
    local w,h=love.graphics.getWidth(),love.graphics.getHeight(); local bg=Assets.get("background"); if bg then Assets.drawImage(bg,w/2,h/2,w,h,0,1) else love.graphics.clear(.004,.007,.02) end; local a,b=Assets.get("starsA"),Assets.get("starsB"); if a then Assets.drawImage(a,w/2,h/2,w,h,0,.28) end; if b then Assets.drawImage(b,w/2,h/2,w,h,0,.16) end; local p=Assets.get("planet"..string.format("%02d",math.floor(time/6)%10)); if p then Assets.drawImage(p,w*.8+math.sin(time*.07)*35,h*.28,190,190,time*.03,.23) end; local l=Assets.get("light"..(math.floor(time*1.5)%11)); if l then Assets.drawImage(l,w*.2,h*.35,350,350,time*.02,.05) end; local n=Assets.get("noise"..string.format("%02d",math.floor(time*4)%28)); if n then Assets.drawImage(n,w/2,h/2,w,h,0,.025) end
end
local function world() space(); for _,p in ipairs(powerups) do p:draw() end; for _,d in ipairs(drones) do d:draw() end; player:draw(Assets.get("player")); for _,b in ipairs(bullets) do b:draw() end; for _,e in ipairs(enemies) do e:draw(player.x,player.y) end; particles:draw(); safe(effects,"draw") end
local function hud() local w,h=love.graphics.getWidth(),love.graphics.getHeight(); local m=Modes.get(run.id); panel(15,15,420,95,.72); love.graphics.setFont(F(18)); love.graphics.setColor(.7,.9,1); love.graphics.print(m.name,30,27); love.graphics.setFont(F(30)); love.graphics.setColor(1,1,1); love.graphics.print("WAVE "..run.wave,30,51); love.graphics.setFont(F(16)); love.graphics.setColor(1,.85,.25); love.graphics.print("SCORE "..run.score,180,30); love.graphics.setColor(.8,.8,.9); love.graphics.print("KILLS "..run.kills,180,57); love.graphics.setColor(1,.3,.35); love.graphics.print("HP "..math.ceil(player.health).."/"..player.maxHealth,270,30); love.graphics.setColor(.8,.75,1); love.graphics.print("x"..run.combo,315,57); love.graphics.setColor(.6,.85,1); love.graphics.print("LIVES "..run.lives,270,78); if run.id=="gauntlet" then panel(w-285,15,270,86,.72); love.graphics.setFont(F(16)); love.graphics.setColor(.9,.45,1); love.graphics.print(run.mutator.name,w-270,27); love.graphics.setFont(F(12)); love.graphics.setColor(.82,.82,.9); love.graphics.printf(run.mutator.desc,w-270,50,240,"left"); love.graphics.printf(string.format("TRIAL %d/8  %ds",run.trial,math.max(0,run.trialDuration-run.trialTimer)),w-270,78,240,"left") end; if waveText>0 then love.graphics.setFont(F(44)); love.graphics.setColor(.5,.9,1,clamp(waveText/1.2,0,1)); love.graphics.printf("WAVE "..run.wave,0,h*.32,w,"center") end; if mobile and touch then touch:draw() end end
local function menu() space(); local w,h=love.graphics.getWidth(),love.graphics.getHeight(); love.graphics.setFont(F(58)); love.graphics.setColor(.3,.85,1,.24); love.graphics.printf("STARFALL VENGEANCE",0,82,w,"center"); love.graphics.setColor(.9,.98,1); love.graphics.printf("STARFALL VENGEANCE",0,78,w,"center"); love.graphics.setFont(F(18)); love.graphics.setColor(.65,.78,.9); love.graphics.printf("SURVIVE • ADAPT • DOMINATE",0,145,w,"center"); button({x=w/2-125,y=h/2-25,w=250,h=58,text="PLAY"}); button({x=w/2-125,y=h/2+50,w=250,h=58,text="HOW TO PLAY"}); button({x=w/2-125,y=h/2+125,w=250,h=58,text="SETTINGS"}) end
local function modeScreen() space(); local w,h=love.graphics.getWidth(),love.graphics.getHeight(); love.graphics.setFont(F(44)); love.graphics.setColor(.82,.95,1); love.graphics.printf("SELECT YOUR RUN",0,55,w,"center"); for i,id in ipairs(modeIds) do local m=Modes.get(id); local x=w/2-430+(i-1)*290; local c=Modes.modeColor(id); panel(x,150,260,345,i==selectedMode and .9 or .7); love.graphics.setFont(F(26)); love.graphics.setColor(c[1],c[2],c[3]); love.graphics.printf(m.name,x,175,260,"center"); love.graphics.setFont(F(14)); love.graphics.setColor(.84,.9,.96); love.graphics.printf(m.tagline,x+20,220,220,"center"); love.graphics.setColor(.66,.73,.82); love.graphics.printf(m.description,x+20,270,220,"center"); love.graphics.setColor(c[1],c[2],c[3]); love.graphics.printf(m.goal,x+20,390,220,"center"); button({x=x+30,y=435,w=200,h=40,text="SELECT"},c) end; button({x=w/2-90,y=h-55,w=180,h=40,text="BACK"},{.3,.42,.55}) end
local function upgradeScreen() world(); local w,h=love.graphics.getWidth(),love.graphics.getHeight(); love.graphics.setColor(0,0,0,.78); love.graphics.rectangle("fill",0,0,w,h); love.graphics.setFont(F(46)); love.graphics.setColor(1,.9,.35); love.graphics.printf("LEVEL UP",0,70,w,"center"); local choices=_G.__SV_CHOICES or {}; for i,u in ipairs(choices) do local x=w/2-410+(i-1)*280; panel(x,190,250,210,.92); love.graphics.setFont(F(18)); love.graphics.setColor(.35,.85,1); love.graphics.printf(u.name,x+15,215,220,"center"); love.graphics.setFont(F(13)); love.graphics.setColor(.8,.85,.92); love.graphics.printf(u.description,x+20,270,210,"center"); love.graphics.setFont(F(11)); love.graphics.setColor(.55,.65,.75); love.graphics.printf("CLICK TO INSTALL",x+20,365,210,"center") end end
local function overScreen() space(); local w,h=love.graphics.getWidth(),love.graphics.getHeight(); love.graphics.setColor(0,0,0,.74); love.graphics.rectangle("fill",0,0,w,h); love.graphics.setFont(F(60)); love.graphics.setColor(run.completed and .3 or 1,run.completed and .95 or .25,run.completed and 1 or .3); love.graphics.printf(run.completed and "VICTORY" or "GAME OVER",0,75,w,"center"); love.graphics.setFont(F(18)); love.graphics.setColor(.75,.85,.95); love.graphics.printf(reason,0,145,w,"center"); panel(w/2-250,195,500,225,.9); love.graphics.setFont(F(36)); love.graphics.setColor(1,.86,.3); love.graphics.printf(tostring(run.score),w/2-230,225,460,"center"); love.graphics.setFont(F(16)); love.graphics.setColor(.8,.85,.9); love.graphics.printf("Wave "..run.wave.." • "..run.kills.." kills • Best combo x"..run.bestCombo,w/2-230,305,460,"center"); if newBest then love.graphics.setColor(1,.85,.25); love.graphics.printf("★ NEW PERSONAL BEST ★",w/2-230,348,460,"center") end; button({x=w/2-220,y=465,w=200,h=55,text="RETRY"}); button({x=w/2+20,y=465,w=200,h=55,text="MENU"},{.3,.42,.58}) end
local function help() space(); local w,h=love.graphics.getWidth(),love.graphics.getHeight(); panel(w/2-420,80,840,500,.92); love.graphics.setFont(F(40)); love.graphics.setColor(.7,.9,1); love.graphics.printf("HOW TO PLAY",0,110,w,"center"); love.graphics.setFont(F(17)); love.graphics.setColor(.82,.88,.94); love.graphics.printf("WASD / ARROWS — MOVE\nMOUSE — AIM + FIRE\nSPACE — DASH\n1–4 — SWITCH WEAPON\nESC — PAUSE\n\nCAMPAIGN — 30 waves\nENDLESS — infinite adaptive pressure\nGAUNTLET — 8 timed mutator trials\n\nChain kills for combo score. Grab power-ups.\nLevel up to install permanent run upgrades.",w/2-350,190,700,"center"); button({x=w/2-90,y=520,w=180,h=45,text="BACK"},{.3,.45,.65}) end
local function settings() space(); local w,h=love.graphics.getWidth(),love.graphics.getHeight(); panel(w/2-280,90,560,470,.92); love.graphics.setFont(F(44)); love.graphics.setColor(.8,.95,1); love.graphics.printf("SETTINGS",0,120,w,"center"); local st=sound:getSettings(); button({x=w/2-180,y=220,w=360,h=50,text="SOUND: "..(st.soundEnabled and "ON" or "OFF")}); button({x=w/2-180,y=290,w=360,h=50,text="MUSIC: "..(st.musicEnabled and "ON" or "OFF")}); button({x=w/2-180,y=360,w=360,h=50,text="QUALITY: "..quality:upper()}); button({x=w/2-180,y=450,w=360,h=50,text="BACK"},{.3,.42,.55}) end
function love.load() math.randomseed(os.time()); Assets.load(); sound=Sound.new(); particles=Particles.new(); effects=Effects.new(); camera=Camera.new(); local os=love.system.getOS(); mobile=(os=="Android" or os=="iOS"); if mobile then touch=TouchControls.new() end; quality="high"; Profile.init(); local p=Profile.getProfile(); best=p and p.bestScore or 0; love.mouse.setVisible(true) end
function love.update(dt) dt=math.min(dt or .016,.05); time=time+dt; if waveText>0 then waveText=math.max(0,waveText-dt) end; if flashT>0 then flashT=math.max(0,flashT-dt*2.5) end; safe(particles,"update",dt); safe(effects,"update",dt); safe(camera,"update",dt); if state=="playing" then combat(dt) end end
function love.draw() love.graphics.clear(0,0,0); if state=="menu" then menu() elseif state=="modes" then modeScreen() elseif state=="playing" then world(); hud() elseif state=="upgrade" then upgradeScreen() elseif state=="gameover" then overScreen() elseif state=="help" then help() elseif state=="settings" then settings() elseif state=="paused" then world(); love.graphics.setColor(0,0,0,.65); love.graphics.rectangle("fill",0,0,love.graphics.getWidth(),love.graphics.getHeight()); local w=love.graphics.getWidth(); love.graphics.setFont(F(56)); love.graphics.setColor(1,1,1); love.graphics.printf("PAUSED",0,155,w,"center"); button({x=w/2-110,y=250,w=220,h=50,text="RESUME"}); button({x=w/2-110,y=320,w=220,h=50,text="QUIT RUN"},{.3,.42,.55}) end; if flashT>0 then love.graphics.setColor(flash[1],flash[2],flash[3],flashT*.12); love.graphics.rectangle("fill",0,0,love.graphics.getWidth(),love.graphics.getHeight()) end end
function love.mousepressed(x,y,b) if b~=1 then return end; local w,h=love.graphics.getWidth(),love.graphics.getHeight(); if state=="menu" then if inr(x,y,{x=w/2-125,y=h/2-25,w=250,h=58}) then state="modes" elseif inr(x,y,{x=w/2-125,y=h/2+50,w=250,h=58}) then state="help" elseif inr(x,y,{x=w/2-125,y=h/2+125,w=250,h=58}) then state="settings" end elseif state=="modes" then for i=1,3 do local x0=w/2-430+(i-1)*290; if inr(x,y,{x=x0,y=150,w=260,h=345}) then selectedMode=i; if y>=435 then startRun() end; return end end; if inr(x,y,{x=w/2-90,y=h-55,w=180,h=40}) then state="menu" end elseif state=="playing" then mouseDown=true elseif state=="upgrade" then local choices=_G.__SV_CHOICES or {}; for i,u in ipairs(choices) do local x0=w/2-410+(i-1)*280; if inr(x,y,{x=x0,y=190,w=250,h=210}) then pcall(u.apply,player); addDrones(); state="playing"; return end end elseif state=="gameover" then if inr(x,y,{x=w/2-220,y=465,w=200,h=55}) then startRun() elseif inr(x,y,{x=w/2+20,y=465,w=200,h=55}) then state="menu" end elseif state=="help" then state="menu" elseif state=="settings" then if inr(x,y,{x=w/2-180,y=220,w=360,h=50}) then sound:toggleSound() elseif inr(x,y,{x=w/2-180,y=290,w=360,h=50}) then sound:toggleMusic() elseif inr(x,y,{x=w/2-180,y=360,w=360,h=50}) then quality=(quality=="high" and "medium") or (quality=="medium" and "low") or "high"; particles:setQuality(quality); effects:setQuality(quality); camera:setQuality(quality) elseif inr(x,y,{x=w/2-180,y=450,w=360,h=50}) then state="menu" end elseif state=="paused" then if inr(x,y,{x=w/2-110,y=250,w=220,h=50}) then state="playing" elseif inr(x,y,{x=w/2-110,y=320,w=220,h=50}) then state="menu" end end end
function love.mousereleased(_,_,b) if b==1 then mouseDown=false end end
function love.keypressed(k) if k=="escape" then if state=="playing" then state="paused" elseif state=="paused" then state="playing" elseif state=="help" or state=="settings" or state=="modes" then state="menu" end; return end; if state=="playing" then if k=="1" then currentWeapon="pistol" elseif k=="2" and weapons.shotgun.unlocked then currentWeapon="shotgun" elseif k=="3" and weapons.machinegun.unlocked then currentWeapon="machinegun" elseif k=="4" and weapons.sniper.unlocked then currentWeapon="sniper" elseif k=="space" then dash() end elseif state=="modes" then if k=="left" or k=="a" then selectedMode=(selectedMode-2)%3+1 elseif k=="right" or k=="d" then selectedMode=selectedMode%3+1 elseif k=="return" or k=="space" then startRun() end end end
function love.touchpressed(id,x,y) if mobile and touch then if state=="playing" then touch:touchpressed(id,x,y) else love.mousepressed(x,y,1) end end end
function love.touchmoved(id,x,y) if mobile and touch and state=="playing" then touch:touchmoved(id,x,y) end end
function love.touchreleased(id) if mobile and touch and state=="playing" then touch:touchreleased(id) end end
return nil
